### ISSUE TITLE
Sanger Imputation Service issue

### ISSUE THREAD

**Issue by faridrashidi** [hxj5/xcltk#6]
Dear xcltk developers,

First of all thank you for developing such an amazing tool along with XClone. The documentation is great!
I have encountered an issue while trying to upload the VCF file generated from the baf_pre_phase.sh script. I am unsure of how to resolve this problem since I used the reference genome you mentioned that is compatible with Sanger. Could you please suggest some solutions?

```
--- Aborted Job ---
  The genotype probability distribution in the input file does not match the reference
  panel frequencies well. The number of genotypes expected with low frequencies under HWE
  (with P<=0.1) is too big in the user data: 0.32 whereas the threshold is 0.26. For comparison,
  the number of these genotypes in 1000Genomes data is 0.17, the attached plot shows typical
  GT distributions

  This is usually an indicator of REF,ALT alleles being on incorrect strand. Another frequent
  problem is the VCF using a different reference sequence, for example GRCh38 instead of GRCh37.
```

I also have another question regarding `xcltk basefc` parameter `-r  <region file>`, would it be possible to provide some example of what this file should be?

**Comment by hxj5** [comment]
Hi, thanks for your feedback. For the Sanger phasing issue, could you share detailed information of your single cell dataset (e.g., is it 10x scRNA-seq or SMART-seq; aligned to hg19 or hg38; etc...) and the cmdline options you used when running `baf_pre_phase.sh`. 

For `basefc`, the `-r <region file>` could be either a [BED file](https://en.wikipedia.org/wiki/BED_(file_format)) (set `-T bed`) or a TSV file (set `-T tsv`). The TSV file should contain three tab-delimed columns: \<chrom\> \<start\> \<end\>, and both \<start\> and \<end\> are 1-based genomic positions and included. Note that files of both formats should not contain header. 

An example of BED file:
```
chr1	0	1000
chr1	1000	2000
chr1	2000	3000
```

Its equivalent TSV file is:
```
chr1	1	1000
chr1	1001	2000
chr1	2001	3000
```

BTW, the latest manual of xcltk preprocessing is at [xcltk/preprocess](https://github.com/hxj5/xcltk/tree/master/preprocess).

**Comment by faridrashidi** [comment]
Thank you for your response. My dataset was aligned to hg38 and I used the following command to run `baf_pre_phase.sh`:

```
baf_pre_phase.sh \
    -N H08 \
    -s H08.bam \
    -b H08_barcodes.tsv \
    -F human_g1k_v37.fasta \
    -O H08_output \
    -g 38 \
    -C CB \
    -u UB \
    -p 16
```

Thank you for providing the format of region file in `basefc`. Could you also please clarify what this file represents? Does it contain the regions of entire genes? Do you have any recommendation for what to provide as a default?

**Comment by hxj5** [comment]
The `basefc` input is indeed the whole list of features (typically genes). You may use your own gene list file or our pre-compiled file `annotate_genes_hg19_update_20230126.txt` and `annotate_genes_hg38_update_20230126.txt` at [xcltk/preprocess/data/](https://github.com/hxj5/xcltk/tree/master/preprocess/data). Select the right genomic version and set `basefc -T tsv` as the file is in TSV format.

For the phasing issue, the `baf_pre_phase.sh` cmdline looks fine, assuming the BAM file was generated by typical CellRanger pipeline. Does your VCF file submitted to the phasing server have a filename suffix "*.fixref.sort.vcf.gz"? (file with that suffix is the final output of the pre_phase script).

**Comment by hxj5** [comment]
Thanks for sharing the example VCF, it looks fine. 

Could you also share the logging file for double checking whether every step in the script worked well, especially the "fixref" step indicated in the sanger report.

"_This is usually an indicator of REF,ALT alleles being on incorrect strand. Another frequent problem is the VCF using a different reference sequence, for example GRCh38 instead of GRCh37._"

You may also run "fixref" on your submitted VCF by yourself (see the "Check and fix the REF allele" paragraph on [Sanger phasing resources page](https://imputation.sanger.ac.uk/?resources=1) for details).

**Comment by faridrashidi** [comment]
Thank you so much for your response Xianjie. I had to rerun the command again since I didn't keep the log but now it can be downloaded from [log.txt](https://drive.google.com/file/d/1ZQTfuc_n0KeFckOe7Zu7MVLrjuBR4SLc/view?usp=share_link). It seem sthe `fixref` step was successfully done, what do you think?

**Comment by hxj5** [comment]
Thanks for your efforts to generate the log file. It seems every step works well.

Then I would suggest you checking "fixref" status (bcftools +fixref) and "genotype frequencies" (bcftools +af-dist) of the VCF, following the official instructions (see the "Check and fix the REF allele" paragraph on [Sanger phasing resources page](https://imputation.sanger.ac.uk/?resources=1) for details).

On the other hand, there may be some mismatches between the sequenced data and sanger refernece panel, as indicated on [this Biostars thread](https://www.biostars.org/p/337281/). You may try selecting different reference panels on sanger service page.

**Comment by faridrashidi** [comment]
Thanks Xianjie for your suggestions.

1) I did run `bcftools +fixref` but everything appeared to be ok.
2) Unfortunately, I encountered an issue while attempting to run `bcftools +af-dist`. The URL for the 1000 Genomes allele frequency annotations is broken and cannot be downloaded.
3) I also looked into other reference panels on Sanger, but encountered the same error.

Is there anyway to run `xcltk` and `XClone` using a common SNP VCF file on my local machine instead of the Sanger Server? Something similar to `Numbat`?

**Comment by hxj5** [comment]
Thanks for your updates. 

1. We are testing performing reference phasing on local machine, similar to Numbat as you mentioned, to make the phasing process smoother. However, evaluating the new strategy may take some time. For now, you may want to use an alternative method for phasing, given the results you listed.
2. Since xcltk preprocessing framework is designed to be divided into three parts (pre-phase, phase, and post-phase), it should be flexible to use a different phasing method, such as Eagle2 used in Numbat, before the post-phase step. For example, if you have results of Numbat preprocessing pipeline, you may try merging all the phased VCF files (in the `<output_dir_of_Numbat_preprocess>/phasing` dir) into one new VCF as input of `baf_post_phase.sh`.
3. (Optional) you may phase the VCF submitted to Sanger server with Eagle2 on local machine, to check whether the VCF could be phased smoothly.

**Comment by faridrashidi** [comment]
Thank you Xianjie. I do already have the phasing files according to hg38 from Numbat and now attempting to use the merged VCF as input for `baf_post_phase.sh`. However, I'm unsure whether I need to modify the `baf_post_phase.sh` script and ignore lines 170 to 184 (which are for liftover). Can you advise me on this matter?

**Comment by hxj5** [comment]
Hi, you may set `-g 38` and `-G 38` for the updated `baf_post_phase.sh` to skip liftover (commit ec1ebe1). For details of each option, you can type `./baf_post_phase.sh -h`.

**Comment by faridrashidi** [comment]
Hi Xianjie, I just wanted to let you know that after switching to python 3.7 my initial issue with sanger imputation server was miraculously solved! It seems both XClone and xcltk must be run using only python 3.7. Thank you for your help anyway.

**Comment by hxj5** [comment]
Thanks for the updates. It is very helpful.
