### ISSUE TITLE
Got error when I run xcltk 

### ISSUE THREAD

**Issue by chupan1218** [hxj5/xcltk#8]
Hi,

I have successfully installed xcltk on my local computer. However, when I attempted to run the tool with the necessary parameters, I encountered some errors as following: 

[I::pipeline::pipeline_wrapper] xcltk BAF preprocessing starts ...
[I::pipeline::pipeline_wrapper] check args ...
Traceback (most recent call last):
  File "/Users/cpan/opt/anaconda3/envs/xcltk/bin/xcltk", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/cpan/opt/anaconda3/envs/xcltk/lib/python3.11/site-packages/xcltk/xcltk.py", line 49, in main
    elif command == "baf": baf_baf(sys.argv)
                           ^^^^^^^^^^^^^^^^^
  File "/Users/cpan/opt/anaconda3/envs/xcltk/lib/python3.11/site-packages/xcltk/baf/pipeline.py", line 118, in pipeline_main
    ret = pipeline_wrapper(
          ^^^^^^^^^^^^^^^^^
  File "/Users/cpan/opt/anaconda3/envs/xcltk/lib/python3.11/site-packages/xcltk/baf/pipeline.py", line 152, in pipeline_wrapper
    assert_n(label)
  File "/Users/cpan/opt/anaconda3/envs/xcltk/lib/python3.11/site-packages/xcltk/utils/base.py", line 9, in assert_n
    assert x is not None and len(x) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

For context, I can run cellsnp-lite successfully on the same system, which suggests that the general setup is functional. However, given the enhancements in xcltk, I am eager to transition to using this tool. Please help me check this problem, thanks a lot!

Best,
Chu

**Comment by hxj5** [comment]
Hi, thanks for your feedback. It seems the `--label` option was not properly set. Could you share the xcltk version and the command line you used?

To run the xcltk BAF pipeline, you can check out the section "[Quick Start](https://github.com/hxj5/xcltk/tree/master/preprocess#quick-start)" in the manual `xcltk/preprocess/README.md`.

**Comment by chupan1218** [comment]
Hi, thanks for the quick response. I used xcltk (version 0.3.1) to genotype my single cells in single-cell RNA-seq data. Below is the command line I used:
xcltk baf \
      --label G522 \
      --sam /Users/cpan/Documents/su2cProj/xcltk/gex_possorted_bam.bam \ 
      --barcode /Users/cpan/Documents/su2cProj/xcltk/barcodes.tsv \
      --snpvcf /Users/cpan/Documents/su2cProj/xcltk/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf.gz \ 
      --region /Users/cpan/Documents/su2cProj/xcltk/annotate_genes_hg38_update_20230126.txt \
      --outdir /Users/cpan/Documents/su2cProj/xcltk/outputs \ 
      --gmap /Users/cpan/Documents/su2cProj/xcltk/Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz \
      --eagle /Users/cpan/Documents/su2cProj/xcltk/Eagle_v2.4.1/eagle \
      --paneldir /Users/cpan/Documents/su2cProj/xcltk/1000G_hg38 \
      --ncores 2

**Comment by hxj5** [comment]
Hi, it seems several ending backslash symbols were missing. You may add them and re-run.

**Comment by chupan1218** [comment]
Hi, I still encountered the same error when I run the command line like this: 
xcltk baf --label G522 --sam /Users/cpan/Documents/su2cProj/xcltk/gex_possorted_bam.bam --barcode /Users/cpan/Documents/su2cProj/xcltk/barcodes.tsv --snpvcf /Users/cpan/Documents/su2cProj/xcltk/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf.gz --region /Users/cpan/Documents/su2cProj/xcltk/annotate_genes_hg38_update_20230126.txt --outdir /Users/cpan/Documents/su2cProj/xcltk/outputs --gmap /Users/cpan/Documents/su2cProj/xcltk/Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz --eagle /Users/cpan/Documents/su2cProj/xcltk/Eagle_v2.4.1/eagle --paneldir /Users/cpan/Documents/su2cProj/xcltk/1000G_hg38 --ncores 2

**Comment by chupan1218** [comment]
Maybe it was the python I used that given rise to this issue! I am trying to figure it out. Thanks for help!!!

**Comment by chupan1218** [comment]
Hi, I have solved my issue! Thanks again!
